#!/usr/bin/env node
// Generate Maestro flows for the 3 e2e scenarios × 6 data-layer variants.
// Each variant is selected at launch via the deep link `gqlharness://home?variant=<id>`.
//
//   node scripts/gen-flows.mjs
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'maestro');
mkdirSync(OUT, { recursive: true });

const APP_ID = 'com.perf.gqlharness';
const VARIANTS = ['vanilla', 'tanstack', 'rtk', 'zustand', 'jotai', 'relay'];

// Wait (up to timeout) for an element by id to appear.
function waitId(id, timeout = 20000) {
  return `- extendedWaitUntil:
    visible:
      id: "${id}"
    timeout: ${timeout}
`;
}
function waitText(text, timeout = 15000) {
  return `- extendedWaitUntil:
    visible: "${text}"
    timeout: ${timeout}
`;
}
// Scroll (up to timeout) until an element by id is visible.
function scrollToId(id, timeout = 15000) {
  return `- scrollUntilVisible:
    element:
      id: "${id}"
    direction: DOWN
    timeout: ${timeout}
`;
}

function header(variant) {
  return `# AUTO-GENERATED by scripts/gen-flows.mjs — variant=${variant}
appId: ${APP_ID}
---
- launchApp:
    clearState: true
- openLink: "gqlharness://home?variant=${variant}"
` + waitId(`app-${variant}`, 20000);
}

// Test 1: open → tap first TOP_GAINERS asset → wait → back to home.
function test1(variant) {
  return (
    header(variant) +
    waitId('section-TOP_GAINERS', 20000) +
    `- tapOn:
    id: "row-TOP_GAINERS-0"
` +
    waitId('detail-scroll', 15000) +
    waitId('detail-description', 15000) +
    `- tapOn:
    id: "btn-back"
` +
    waitId('home-scroll', 10000)
  );
}

// Test 2: open → scroll to bottom → tap the last (RECENTLY_LISTED index 3) asset.
function test2(variant) {
  return (
    header(variant) +
    // Give the home data a beat to load before scrolling.
    waitId('section-TOP_GAINERS', 20000) +
    scrollToId('row-RECENTLY_LISTED-3', 15000) +
    `- tapOn:
    id: "row-RECENTLY_LISTED-3"
` +
    waitId('detail-scroll', 15000) +
    waitId('detail-description', 15000)
  );
}

// Test 3 (authed): sign in → tap first TOP_LOSERS → add to watchlist → back →
// re-open same asset → confirm watching → unwatch → back.
function test3(variant) {
  return (
    header(variant) +
    `- tapOn:
    id: "btn-signin"
` +
    waitId('signin-screen', 8000) +
    `- tapOn:
    id: "input-email"
- inputText: "perf@example.com"
- tapOn:
    id: "input-password"
- inputText: "password123"
- tapOn:
    id: "btn-submit-signin"
` +
    waitId('balance-value', 10000) +
    waitId('section-TOP_GAINERS', 20000) +
    scrollToId('row-TOP_LOSERS-0', 15000) +
    `- tapOn:
    id: "row-TOP_LOSERS-0"
` +
    waitId('btn-watch-toggle', 15000) +
    `- tapOn:
    id: "btn-watch-toggle"
` +
    waitText('★ Watching', 8000) +
    `- tapOn:
    id: "btn-back"
` +
    waitId('home-scroll', 10000) +
    scrollToId('row-TOP_LOSERS-0', 15000) +
    `- tapOn:
    id: "row-TOP_LOSERS-0"
` +
    waitText('★ Watching', 15000) +
    `- tapOn:
    id: "btn-watch-toggle"
` +
    waitText('☆ Add to watchlist', 8000) +
    `- tapOn:
    id: "btn-back"
` +
    waitId('home-scroll', 10000)
  );
}

const tests = { t1: test1, t2: test2, t3: test3 };

let count = 0;
for (const variant of VARIANTS) {
  for (const [t, fn] of Object.entries(tests)) {
    writeFileSync(resolve(OUT, `${variant}__${t}.yaml`), fn(variant));
    count++;
  }
}
console.log(`wrote ${count} flows to ${OUT}`);
